{
 "title": "New dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{action=\"GetAll\",job=\"todoapi\"}[5m])) by (le))*100"
    }
   ]
  },
  {
   "title": "Data Read Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(webapi_database_read_duration_seconds_bucket{le=\"+Inf\"}[5m])) by (le)) unless sum(rate(webapi_database_read_duration_seconds_bucket{le=\"+Inf\"}[5m])) by (le) == 0"
    }
   ]
  },
  {
   "title": "Data Created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "todo_entry_created{job=\"todoapi\"}"
    }
   ]
  },
  {
   "title": "Requests Received",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_received_total{job=\"todoapi\"}",
     "legendFormat": "{{action}}"
    }
   ]
  }
 ]
}